[package]
name = "osu-parser"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osu-types = { path = "../osu-types" }
thiserror = "1.0.29"